version: "2"
services:
 zoo1:
   image: wurstmeister/zookeeper:3.4.6
   privileged: true
 kafka1:
   image: wurstmeister/kafka:0.9.0.1
   privileged: true
   environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_CREATE_TOPICS: "THE.TEST:20:2"
 kafka2:
   image: wurstmeister/kafka:0.9.0.1
   privileged: true
   environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_CREATE_TOPICS: "THE.TEST:20:2"
 kafka3:
   image: wurstmeister/kafka:0.9.0.1
   privileged: true
   environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_CREATE_TOPICS: "THE.TEST:20:2"
 our-service1:
   build: our-service
 fake:
   build: fake
   ports:
    - 3001:80